// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.8.0.0
//      SpecFlow Generator Version:3.8.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Corvus.Extensions.Json.Specs
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.8.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("StandardConversion for SystemTextJson")]
    [NUnit.Framework.CategoryAttribute("perFeatureContainer")]
    public partial class StandardConversionForSystemTextJsonFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "perFeatureContainer"};
        
#line 1 "StandardConversion.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "StandardConversion for SystemTextJson", "\tIn order to ensure common serialization specifications\r\n\tAs a developer\r\n\tI want" +
                    " to be provided with standard serializer settings", ProgrammingLanguage.CSharp, new string[] {
                        "perFeatureContainer"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Serialize an object with convertible properties")]
        [NUnit.Framework.TestCaseAttribute("Hello there", "2018-04-15T09:09:31.234+01:00", "2018-04-15T09:09:31.234+01:00", "en-US", "Second", @"{""someValue"":""Hello there"",""someDateTime"":{""dateTimeOffset"":""2018-04-15T09:09:31.234+01:00"",""unixTime"":1523779771234},""someNullableDateTime"":{""dateTimeOffset"":""2018-04-15T09:09:31.234+01:00"",""unixTime"":1523779771234},""someCulture"":""en-US"",""someEnum"":""second""}", null)]
        [NUnit.Framework.TestCaseAttribute("Hello there", "2018-04-15T09:09:31.234+01:00", "2018-04-15T09:09:31.234+01:00", "en-US", "Second", @"{""someValue"":""Hello there"",""someDateTime"":{""dateTimeOffset"":""2018-04-15T09:09:31.234+01:00"",""unixTime"":1523779771234},""someNullableDateTime"":{""dateTimeOffset"":""2018-04-15T09:09:31.234+01:00"",""unixTime"":1523779771234},""someCulture"":""en-US"",""someEnum"":""second""}", null)]
        [NUnit.Framework.TestCaseAttribute("Hello there", "2018-04-15T09:09:31.234+01:00", "", "", "Second", "{\"someValue\":\"Hello there\",\"someDateTime\":{\"dateTimeOffset\":\"2018-04-15T09:09:31." +
            "234+01:00\",\"unixTime\":1523779771234},\"someEnum\":\"second\"}", null)]
        public virtual void SerializeAnObjectWithConvertibleProperties(string someValue, string someDateTime, string someNullableDateTime, string someCulture, string someEnum, string content, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("SomeValue", someValue);
            argumentsOfScenario.Add("SomeDateTime", someDateTime);
            argumentsOfScenario.Add("SomeNullableDateTime", someNullableDateTime);
            argumentsOfScenario.Add("SomeCulture", someCulture);
            argumentsOfScenario.Add("SomeEnum", someEnum);
            argumentsOfScenario.Add("Content", content);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Serialize an object with convertible properties", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
 testRunner.Given(string.Format("I serialize a POCO with \"{0}\", \"{1}\", \"{2}\", \"{3}\", \"{4}\"", someValue, someDateTime, someNullableDateTime, someCulture, someEnum), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 10
 testRunner.Then(string.Format("the result should be \"{0}\"", content), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Deserialize an object with convertible properties")]
        [NUnit.Framework.TestCaseAttribute("Hello there", "2018-04-15T09:09:31.234+01:00", "2018-04-15T09:09:31.234+01:00", "en-US", "Second", @"{""someValue"":""Hello there"",""someDateTime"":{""dateTimeOffset"":""2018-04-15T09:09:31.234+01:00"",""unixTime"":1523779771234},""someNullableDateTime"":{""dateTimeOffset"":""2018-04-15T09:09:31.234+01:00"",""unixTime"":1523779771234},""someCulture"":""en-US"",""someEnum"":""second""}", null)]
        [NUnit.Framework.TestCaseAttribute("Hello there", "2018-04-15T09:09:31.234+01:00", "2018-04-15T09:09:31.234+01:00", "en-US", "Second", "{\"someValue\":\"Hello there\",\"someDateTime\":\"2018-04-15T09:09:31.2340000+01:00\",\"so" +
            "meNullableDateTime\":\"2018-04-15T09:09:31.234+01:00\",\"someCulture\":\"en-US\",\"someE" +
            "num\":\"second\"}", null)]
        [NUnit.Framework.TestCaseAttribute("Hello there", "2018-04-15T09:09:31.234+01:00", "", "en-US", "Second", "{\"someValue\":\"Hello there\",\"someDateTime\":{\"dateTimeOffset\":\"2018-04-15T09:09:31." +
            "234+01:00\",\"unixTime\":1523779771234},\"someCulture\":\"en-US\",\"someEnum\":\"second\"}", null)]
        [NUnit.Framework.TestCaseAttribute("Hello there", "2018-04-15T09:09:31.234+01:00", "", "", "Second", "{\"someValue\":\"Hello there\",\"someDateTime\":{\"dateTimeOffset\":\"2018-04-15T09:09:31." +
            "234+01:00\",\"unixTime\":1523779771234},\"someCulture\":null,\"someEnum\":\"second\"}", null)]
        public virtual void DeserializeAnObjectWithConvertibleProperties(string someValue, string someDateTime, string someNullableDateTime, string someCulture, string someEnum, string content, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("SomeValue", someValue);
            argumentsOfScenario.Add("SomeDateTime", someDateTime);
            argumentsOfScenario.Add("SomeNullableDateTime", someNullableDateTime);
            argumentsOfScenario.Add("SomeCulture", someCulture);
            argumentsOfScenario.Add("SomeEnum", someEnum);
            argumentsOfScenario.Add("Content", content);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deserialize an object with convertible properties", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
 testRunner.Given(string.Format("I deserialize a POCO with the json string \"{0}\"", content), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
 testRunner.Then(string.Format("the result should have values \"{0}\", \"{1}\", \"{2}\", \"{3}\", \"{4}\"", someValue, someDateTime, someNullableDateTime, someCulture, someEnum), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
